### PR TITLE
UICHKIN-272 send ISO-8601 dates in API requests

### PR DESCRIPTION
**Pull request by zburke**
Replace `moment.format()` with `moment.toISOString()` because the
former does not guarantee the numbering system will be `Latn` (0-9,
Arabic numbers). Documentation not withstanding
(https://momentjs.com/docs/#/displaying/format/), what `.format()`
actually does is use the same tokens as for ISO-8601 but without
changing the numbering system. Thus, in a locale with a non-Latn
numbering system, e.g. where 0-9 are represented by a-j, a year-format
like `YYYY` could be returned as `cacb` instead of `2021`.

In fact, this is precisely what happens when the locale is set to `ar`
(Arabic, with a numbering system of Arabic-Hindi numerals, denoted
`Arab`, as opposed to Arabic numerals, denoted `Latn` ([don't ask](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numberingSystem))).

Fixes [UICHKIN-272](https://issues.folio.org/browse/UICHKIN-272), refs [FOLIO-3208](https://issues.folio.org/browse/FOLIO-3208)

### CODE REVIEW

**Comment by zburke** [comment]
@Dmitriy-Litvinenko, these BigTest test failures are a mystery to me. I don't see how the changes in this PR can possibly be related, and yet the tests pass on master but not here. Do you have any insight?

**Comment by zburke** [comment]
Special thanks to @Dmitriy-Litvinenko for pointing out the NPE I introduced in Scan.js 🤦 that was causing my test failures.

**Review by mkuklis — APPROVED** [review]
Great work @zburke!

I'm curious could the `now` be defined inside the `buildDateTime` instead of passing it as a last param? I do see that you are using a different `now` to test so I can see how passing a different `now` can be beneficial. Perhaps if it's not present it can be defaulted to `moment().tz(timeZone)` right inside `buildDateTime`?

This is just cosmetic change so not really needed. Nice work!

**Comment by zburke** [comment]
> could the `now` be defined inside the `buildDateTime()`

I made that change in the first place only because I was trying to get at test-coverage on the lines that were changing. But I understand this better now, and I think you're correct that it should be possible to restore the original signature.

**Comment by zburke** [comment]
@mkuklis, thinking through this _again_, the testing situation is much simpler if `buildDateTime()` accepts a `now` parameter because its internal logic hinges on whether the date/time parts and now-timestamp are on the same side of standard-time/DST. Passing `now` as an argument makes this super easy compared to, I think, mocking all those `moment` methods, though mocking is probably The Right Way according to somebody.

**Comment by mkuklis** [comment]
@zburke this is great work! Also thank you for writing these extra tests.

**Pull request merged**
