### PR TITLE
STCLI-85 Simplify test harness

### PR DESCRIPTION
**Pull request by cherewaty**
## Purpose
With https://issues.folio.org/browse/STCLI-85, we want to make set up for BigTest-ing with FOLIO UI modules as easy as possible.

## Approach
Leans on new changes in `stripes-core` to create a simpler `setupApplication()` helper.

## TODOs / Questions
- Needs a proper `stripes-core` release (perhaps with `react-hot-loader` 😉 )
- How can we avoid having to import the typeface and global CSS here?
- Do we want to export `App` from `@folio/stripes-core`?
- Importing from `stripes-config` in a module repo feels wrong
- Should the helper live somewhere else entirely? `@folio/stripes-cli`? `@folio/stripes-bigtest`? Probably not `@folio/stripes-testing` - should leave that as just `nightmare`-specific.

### CODE REVIEW

**Comment by ttamj** [comment]
>Should the helper live somewhere else entirely?

Yes.  I think this is a good idea.

> Probably not @folio/stripes-testing - should leave that as just nightmare-specific.

I disagree.  `stripes-testing` contains nightmare specific code now, that is true.  The current repo structure facilitated its transition from the previous `ui-testing`.  The intent with `stripes-testing` is to hold all stripes testing needs and thus it wasn't named `stripes-nightmare`.  A single go-to resource for stripes related testing and documentation will reduce segmentation.

We can easily move everything currently in `stripes-testing` into a `nightmare` directory, and add a directory for `bigtest` beside it.

**Comment by cherewaty** [comment]
I'm interested in separating the `nightmare` and `karma` setups since they have such different dependencies. The longest part of any `ui-eholdings` `yarn install` is installing `electron`.

**Comment by ttamj** [comment]
That's good point. Hmm...

**Comment by wwilsman** [comment]
> Should the helper live somewhere else entirely?

I think this is a good idea, but presents issues with Mirage (as I've just encountered in stripes-smart-components).

`startMirage` _must_ run before the app mounts, so it is called during `setup`. The `network/start` file is specific to a module so it can auto-import all the `network/*` files. If we move the setup-app helper into a common place, we'd need to either decouple the mirage setup, or build in a way to auto-import from the current module.

I'd like to do the latter so that we can also move all of the common stripes-core mirage routes into the same place where the helper would live.

If we can solve the mirage issue, we could just import the `setupApplication` helper directly from `stripes-core` and reuse that everywhere we need to test with a complete stripes-core setup.

**Comment by ttamj** [comment]
@wwilsman, If I'm reading it right, your work in https://github.com/folio-org/stripes-core/pull/436 appears to alleviate all these questions. Are there any remaining items that need addressing here?

> - How can we avoid having to import the typeface and global CSS here?
> - Do we want to export App from @folio/stripes-core?
> - Importing from stripes-config in a module repo feels wrong
> - Should the helper live somewhere else entirely?

**Comment by wwilsman** [comment]
Actually yea. I think it does address all of these. 

- The typeface and CSS are imported in the `stripes-core` helper.
- We don't need the `App` directly anymore.
- The helper accepts options to modify `stripes-config`.
- And I think it's alright for this helper to live here, but wouldn't be opposed if there was a more appropriate place.

**Comment by ttamj** [comment]
By "live here", you are referring to `setup-application` logic now living in `stripes-core`, correct?  I think stripes-core is appropriate for it.  To move it out, the same questions will open up again.

Independent of this, I'd like to improve how we handle `stripes-config` within stripes-core itself.

**Comment by cherewaty** [comment]
@wwilsman feel free to add a commit here that updates to the simpler `setupApplication()`.

**Comment by wwilsman** [comment]
Hiccup with `clearModules` and `clearConfig` helpers removing pre-existing config. So only the first test would pass because subsequent tests cleared the `ui-checkin` module from `stripes-config`. 

Currently updating it so it retains pre-existing config. Also going to need to update the `withTranslations` helper so that it correctly includes the current module's translations.

**Comment by wwilsman** [comment]
I removed the duplicate setup stuff that is now handled by `stripes-core` (pointed to my branch for various helper improvements).

Three tests are failing for me all related to [this line in `stripes-components`](https://github.com/folio-org/stripes-components/blob/master/lib/MenuItem/MenuItem.js#L17). The MenuItems used here rely on `action` being sent from meta to the UncontrolledDropdown. But it looks like that line wants `onSelectItem` to be required even though the prop-type is not required.

**Pull request merged**
