### PR TITLE
clean up test output

### PR DESCRIPTION
**Pull request by zburke**
* update to current @folio/eslint-config-stripes, and related deps
* import babel-config from @folio/stripes-cli to avoid EXTREMELY NOISY
  config warnings during tests
* do not call `setState` in async functions unles the component is still
  mounted.
* pass required props (`stripes`) to `<TitleManager>`

Test output on a recent PR
(https://github.com/folio-org/ui-checkin/runs/5289168668?check_suite_focus=true)
was so totally overrun with warnings like these that it was impossible
to find the real source of the trouble:
```
Though the "loose" option was set to "false" in your @babel/preset-env config,
it will not be used for @babel/plugin-proposal-private-property-in-object since
the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties,
@babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object
(when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
```

### CODE REVIEW

**Comment by zburke** [comment]
(Tests on this PR are failing ATM because I'm in the middle of publishing stripes-* libraries and it's getting two different versions of `@folio/stripes-core`; should be remedied automatically as soon as I get `@folio/stripes` `v7.1.0` out the door.)

**Comment by zburke** [comment]
<sigh> of course it runs cleanly locally and throws errors in CI. It is The Way.

**Review by Dmytro-Melnyshyn — APPROVED** [review]

**Comment by Stanislau-Snapok** [comment]
Hello @zburke! Me and @Dmitriy-Litvinenko want to discuss this PR on separate call. Can we do that after releases? Thanks in advance!

**Comment by zburke** [comment]
@Stanislau-Snapok , yes, of course reviewing this later is just fine! And, feel free to tell me, "Dude, we've got this. You're stepping on our toes more than you're helping." and I'll get out of the way. I pushed up this branch because I was asked to review #498 but [one of the initial builds failed](https://github.com/folio-org/ui-checkin/actions/runs/1874839691) and the output was so noisy it was hard to assess the reasons why.

**Pull request closed without merging**
